name: build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:


jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'

    - name: Test
      run: |
        go mod tidy -v
        go test -race ./...

    - name: Build
      run: go build ./...

